title: Matt Jani
email: info@mattjani.com
description: >- # this means to ignore newlines until "baseurl:"
  Copywriter, 3D printing enthusiast
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mattjani.com" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: mattjani
github_username:  mahtDFR

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
